name: Build NSSM

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        platform:
          - win32
          - win64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build NSSM
        shell: cmd
        run: |
          msbuild nssm.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }} /m

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nssm-${{ matrix.platform }}
          path: |
            out/Release/win32/nssm.exe
            out/Release/win64/nssm.exe
